### ISSUE TITLE
Crash on Exit [Windows]

### ISSUE THREAD

**Issue by smaragdus** [crow-translate/crow-translate#75] opened 2019-10-23 00:18 UTC
I experience crashes when I exit **Crow Translate** but I do not know whether there might be a bug in the program or my system is to blame. When exiting **Crow Translate** I sometimes get the following error message:

```
Crow Translate has stopped working
A problem caused the program to stop working correctly. Please close the program.
```

screen:

![Crow Translate 2 2 2 - 2019-10-23 - error - 001](https://user-images.githubusercontent.com/9025757/67344968-08745880-f542-11e9-8fad-5d10b75f090f.png)

I will suggest how to try to reproduce the problem:

1. start **Crow Translate**;
2. maximize it from system tray;
3. copy some chunk of text from a web browser;
4. paste the text into **Crow Translate** and get it translated;
5. clear the text boxes using _Clear_ button;
6. close **Crow Translate** to system tray;
7. exit **Crow Translate** from system tray (_Exit_ command);

This happens under Windows 8 x64.

A question is **Crow Translate** version **2.2.2** (**crow-translate-2.2.2-win64.exe**) x64-bit only? If so, why does it suggest to install in _Program Files (x86)_ in stead of in _Program Files_?

**Comment by faezebax** [comment] 2019-10-23 00:27
check the application log and report it here. here is [how to check windows applications logs](https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/)

**Comment by smaragdus** [comment] 2019-10-23 00:47
@faezebax 

```
Log Name:      Application
Source:        Application Error
Date:          2019-10-23 02:58:35
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      smaragdus
Description:
Faulting application name: crow.exe, version: 2.2.2.0, time stamp: 0x5da7453b
Faulting module name: ntdll.dll, version: 6.2.9200.17313, time stamp: 0x5507a832
Exception code: 0xc0000005
Fault offset: 0x0000000000005471
Faulting process id: 0x17edc
Faulting application start time: 0x01d589348e0a4237
Faulting application path: C:\Program Files (x86)\Crow Translate\crow.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: db73e610-f527-11e9-bf9b-6036dd096608
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-10-22T23:58:35.000000000Z" />
    <EventRecordID>77681</EventRecordID>
    <Channel>Application</Channel>
    <Computer>smaragdus</Computer>
    <Security />
  </System>
  <EventData>
    <Data>crow.exe</Data>
    <Data>2.2.2.0</Data>
    <Data>5da7453b</Data>
    <Data>ntdll.dll</Data>
    <Data>6.2.9200.17313</Data>
    <Data>5507a832</Data>
    <Data>c0000005</Data>
    <Data>0000000000005471</Data>
    <Data>17edc</Data>
    <Data>01d589348e0a4237</Data>
    <Data>C:\Program Files (x86)\Crow Translate\crow.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data>
    <Data>db73e610-f527-11e9-bf9b-6036dd096608</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

Attachment - **Crow Translate.evtx** in ZIP archive (**Crow Translate.zip**):
[Crow Translate.zip](https://github.com/crow-translate/crow-translate/files/3759300/Crow.Translate.zip)

I hope this is all the needed information.

**Comment by faezebax** [comment] 2019-10-23 00:55
I hope [this](https://answers.microsoft.com/en-us/windows/forum/all/app-crash-with-ntdlldll/9aa59f80-99a1-4f3c-b2f0-7eb72df05b2a) can help you.

**Comment by smaragdus** [comment] 2019-10-23 00:58
@faezebax 

Thanks. So you think the problem is not in Crow Translate but in faulty system?

**Comment by faezebax** [comment] 2019-10-23 01:01
others problem solved this way, so maybe. after all I am not windows user since 2003.

**Comment by faezebax** [comment] 2019-10-23 01:04
> @faezebax
> 
> Shall I close this issue?

first check it if the problem get solved then close this issue.

**Comment by smaragdus** [comment] 2019-10-23 01:04
Off-topic- I tried to re-install **ntdll.dll** but I got the following error:

```
The module "ntdll.dll" was loaded but the entry-point DllUnregisterServer was not found.

Make sure that "ntdll.dll" is a valid DLL or OCX file and then try again.
```

screen:

![RegSvr32 - 2019-10-23 - error - 001](https://user-images.githubusercontent.com/9025757/67347175-f4ccf000-f549-11e9-9e27-34e1f54e2e58.png)

I will also check if this error persists after I re-boot.

**Comment by faezebax** [comment] 2019-10-23 01:08
1. Type cmd in the search box, and then right click Command prompt select Run as Administrator.
2. Type this in command prompt:
* regsvr32.exe /u ntdll.dll and press Enter key (this will uninstall the file)
* regsvr32.exe ntdll.dll and press Enter key (this will reinstall the file).

**Comment by smaragdus** [comment] 2019-10-23 01:14
@faezebax 

User Account Control is disabled on my machine. I always log in as administrator. I tried to uninstall and reinstall **ntdll.dll** but I got the error I mentioned above.

Anyway, thank you for the tips and the help.

In fact I noticed that when I start Crow Translate and exit it without translating anything the program exits just right. It crashes only after some translation has been made.

**Comment by faezebax** [comment] 2019-10-23 01:16
also try to update your Windows and do a reboot.

**Comment by Shatur95** [comment] 2019-10-23 07:40
Can't reproduce the issue :(
But I using Windows 10 x64.

> A question is Crow Translate version 2.2.2 (crow-translate-2.2.2-win64.exe) x64-bit only? If so, why does it suggest to install in Program Files (x86) in stead of in Program Files?
Thank you, will fix it this evening.

**Closed** 2019-10-23 22:21 UTC
