### ISSUE TITLE
DeepL support

### ISSUE THREAD

**Issue by c-sanchez** [crow-translate/crow-translate#273] opened 2021-03-01 20:04 UTC
It can be good to have DeepL as a translation engine as well, it has great quality of translations, sometimes is better than google even.
![deepl image](https://www.deepl.com/img/logo/DeepL_Logo_darkBlue_v2.svg)
https://www.deepl.com/translator

**Comment by Shatur95** [comment] 2021-03-01 20:13
Duplicate of https://github.com/crow-translate/QOnlineTranslator/issues/6

**Closed by Shatur95** 2021-03-01 20:13 UTC
Labels: enhancement
