### ISSUE TITLE
Button icons not showing

### ISSUE THREAD

**Issue by cryptolog89** [crow-translate/crow-translate#393] opened 2022-02-01 07:47 UTC
When opening the program in Manjaro Xfce, the icons on the buttons are not displayed. When opened in the terminal, it gives an error:
`QHotkey: "Не удалось зарегистрировать Ctrl+Alt+F. Ошибка: BadAccess (attempt to access private resource denied)"
qt.xkb.compose: failed to create compose table
`
![Crow Translate_001](https://user-images.githubusercontent.com/95739837/151930515-8d6e194f-84d6-47cd-b244-5d72fadf4113.png)

**Comment by Shatur** [comment] 2022-02-01 08:09
Duplicate of #330.

**Closed by Shatur** 2022-02-01 08:09 UTC
Labels: bug
