### ISSUE TITLE
Linguee engine support

### ISSUE THREAD

**Issue by hypsinom** [crow-translate/crow-translate#54] opened 2019-09-09 06:34 UTC
no hurry

**Comment by Shatur95** [comment] 2019-09-09 07:48
It looks like Linguee does not provide api for it.

**Comment by hypsinom** [comment] 2019-10-23 17:13
hello, 

https://www.deepl.com/

**Comment by Shatur95** [comment] 2019-10-23 17:20
Duplicate of #24

**Closed** 2019-10-23 17:20 UTC
