### ISSUE TITLE
Translation using Yandex Translate is broken

### ISSUE THREAD

**Issue by drygdryg** [crow-translate/crow-translate#519] opened 2023-03-10 13:54 UTC
## Bug description
Translation using Yandex Translate doesn't work: I keep constantly getting the error message "Session is invalid" or "Error: Engine systems have detected suspicious traffic from your computer network. Please try your request again later." in some cases.

## Steps to reproduce
1. Open Crow Translate.
2. Select "Yandex" in the right bottom combo box.
3. Try to translate any sentence.
4. See error "Session is invalid" or "Error: Engine systems have detected suspicious traffic from your computer network. Please try your request again later." in the text field on the right.

## Expected behavior
The sentence must be translated.

## Screenshots
![image](https://user-images.githubusercontent.com/43933400/224332298-c718f46d-fbf0-4c29-9568-8d2170a43a26.png)

### Environment 1
- OS: Arch Linux rolling.
- Desktop environment: KDE Plasma 5.27.2 with X11.
- Crow Translate version: 2.10.3.
### Environment 2
- OS: Arch Linux rolling.
- Desktop environment: KDE Plasma 5.27.2 with Wayland.
- Crow Translate version: 2.10.3.
### Environment 3
- OS: Windows 7 Ultimate.
- Crow Translate version: 2.9.12.

## Additional context
The problem started showing up a couple of weeks ago.

**Comment by VolkMilit** [comment] 2023-03-10 14:00
Yandex is changed something just week ago or so and it's broken now. Need to be fixed in [QOnlineTranslator](https://github.com/crow-translate/QOnlineTranslator) side.

**Comment by Kristinita** [comment] 2023-03-21 18:19
+1. The problem reproduces for me on Crow Translate 2.10.3 on my Microsoft Windows [Version 10.0.19041.1415] without VPN or by usage:

1. Cloudflare WARP 2022.12.582.0
1. Proton VPN 2.3.2

Google and Lingva Translate are working fine for me via Crow Translate.

Thanks.

**Comment by artenax** [comment] 2023-05-16 10:44
https://translate.yandex.net/api/v1/tr.json/translate?id=4ef9e5b1.64635a3f.befb4bf3.74722d74657874-2-0&srv=tr-text&text=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82.&lang=ru-en
403 Forbidden

code	405
message	"Session is invalid"

https://cloud.yandex.com/en/docs/translate/api-ref/v1/
v1 (DEPRECATED)

**Comment by artenax** [comment] 2023-05-17 05:31
v1 is a deprecated API, but it still works with some parameters. I managed to change the source code file src/qonlinetranslator/src/qonlinetranslator.cpp, recompile and now I have Yandex working.

**Comment by artenax** [comment] 2023-05-17 16:16
So if you fix yandex work, the code will probably be blocked soon. Maybe shouldn't.

**Comment by Shatur** [comment] 2023-05-17 16:18
> So if you fix yandex work, the code will probably be blocked soon. Maybe shouldn't.

This happens with all proprietary services. But I think we should support it, just takes time to adapt to changes and I currently busy with a different project. Feel free to play around with this and submit a PR. Maybe you will manage to get `ucid` from the web version.

**Comment by artenax** [comment] 2023-05-18 05:08
I couldn't get it out of the web version. Or rather, the retrieved URL does not work outside of the browser and there is no ucid parameter. Maybe we should check mobile apps, browser extensions, etc.

I searched for "translate.yandex.net ucid" and found two projects that mention ucid and methods for calculating it.
https://github.com/Animenosekai/translate/blob/main/translatepy/translators/yandex.py
https://github.com/alekssamos/YandexTranslate/blob/master/addon/globalPlugins/yandexTranslate/yandexfreetranslate.py

There is also a script for DeepL
https://github.com/Animenosekai/translate/blob/main/translatepy/translators/deepl.py

**Comment by Shatur** [comment] 2023-05-18 07:22
> I couldn't get it out of the web version. Or rather, the retrieved URL does not work outside of the browser and there is no ucid parameter.

Same here.

>  Maybe we should check mobile apps, browser extensions, etc.

That's a good idea!
I looked into it, looks like it can be just any UUID?

**Comment by VolkMilit** [comment] 2023-05-18 08:32
@artenax, thanks for debugging! Finally manage it to work. https://github.com/crow-translate/QOnlineTranslator/pull/53

**Closed** 2023-05-18 11:25 UTC
Labels: bug
