### ISSUE TITLE
server replied: Too Many Requests

### ISSUE THREAD

**Issue by ayoubelmhamdi** [crow-translate/crow-translate#374] opened 2021-10-16 17:00 UTC
After some attempts, crow stop working!
**Bug description**
```bash
$ crow -t fr "test"

"Error: Error transferring https://translate.googleapis.com/translate_a/single?client=gtx&ie=UTF-8&oe=UTF-8&dt=bd&dt=ex&dt=ld&dt=md&dt=rw&dt=rm&dt=ss&dt=t&dt=at&dt=qc&sl=auto&tl=fr&hl=en&q=test - server replied: Too Many Requests"
test

[ Automatically detect -> French ]
```

**Environment**

- OS: Arch Linux
- Desktop environment: dwm
- Crow Translate version: (e.g. 2.8.7) 

**Additional context**
I think google traduction does not permit cli tool to translate with terminal
I tested with proxy like that 
```bash
$ export https_proxy=http://...:8080
# then
$ crow -t fr "test"
```
but not work

**Comment by Shatur** [comment] 2021-10-16 17:02
Duplicate of #105.

**Closed as completed by Shatur** 2021-10-16 17:02 UTC
Labels: bug
