### ISSUE TITLE
option add dictionary file like BGL (babylon)

### ISSUE THREAD

**Issue by Alexnoj** [crow-translate/crow-translate#641] opened 2023-12-15 08:35 UTC
option add dictionary file like BGL (babylon).
will be more useful and convenient if crow translator will be have [goldendict app](https://github.com/xiaoyifang/goldendict-ng) features.

**Comment by Shatur** [comment] 2023-12-15 08:43
Duplicate of https://github.com/crow-translate/QOnlineTranslator/issues/4.

**Closed by Shatur** 2023-12-15 08:43 UTC
Labels: enhancement
