### ISSUE TITLE
Translate text from clipboard!

### ISSUE THREAD

**Issue by RyanOrigens** [crow-translate/crow-translate#637] opened 2023-12-03 17:08 UTC
I've been utilizing the 'translate selected text' functionality for quite a long time, and it has been serving me well for the past couple of years. However, now I'm having to use virtual machines quite a lot, and as you can imagine, I cannot share the selected text between them. What I can do, though, is share the clipboard. So, if I need to translate something automatically, I would set a hotkey, like Control + C + C. When I press Control + C, it would copy the text to the clipboard, and when I press it a second time, it would automatically translate.

It also allows for translating selected text in certain software, including ported software that doesn't play well with selected text, like Onlyoffice; the 'translate selected text' feature doesn't work there.

**Comment by Shatur** [comment] 2023-12-03 18:10
Duplicate of #343.

**Closed by Shatur** 2023-12-03 18:10 UTC
Labels: enhancement

**Comment by RyanOrigens** [comment] 2023-12-10 11:52
That's a little old; it's been almost four years since this issue was opened, and there has been no progress. Don't you think it would be a good idea to add it to a to-do list, or perhaps leave this more recent issue open so somebody can address it?

**Comment by Shatur** [comment] 2023-12-10 11:59
> it's been almost four years since this issue was opened

I'm not obligated to implement every requested feature.
But feel free to submit a PR for it, I will accept it.

> or perhaps leave this more recent issue open so somebody can address it?

No, I prefer to have a single feature to keep the discussion in one place.
And bumping issues won't help the development.
