### ISSUE TITLE
Global Shortcuts Not working on Wayland

### ISSUE THREAD

**Issue by ZorinArch** [crow-translate/crow-translate#449] opened 2022-06-26 09:57 UTC
Hello,

**Bug description**
I try to use global shortcuts (e.g. CTRL+ALT+E [Translate selected text]) and it NOT working and option related to it from settings are disabled. This only happen on wayland session.

**Expected behavior**
i hope all global shortcuts works properly on wayland like on xorg.

**Environment**
- OS: Arch Linux
- Desktop environment: KDE
- Crow Translate version: 2.9.8

Thanks,

**Comment by Shatur** [comment] 2022-06-26 09:59
Duplicate of #324.

**Closed by Shatur** 2022-06-26 09:59 UTC
Labels: bug
