### ISSUE TITLE
Running on different apps 

### ISSUE THREAD

**Issue by thknx** [crow-translate/crow-translate#81] opened 2019-11-03 10:47 UTC
-Debian GNU/Linux 10 (buster)
-Gnome Desktop Environment.

Crow only works with firefox on my debian. For example when I open any Pdf with Document Viewer or any other application, and press Ctrl+Alt+E Crow is not display anything. But works on firefox.

Should I configure anything?

```
us@debian:~$ crow 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
```

**Comment by faezebax** [comment] 2019-11-03 10:56
I had the same problem on Xorg. I think it works with FF because it is using X too instead of wayland. BTW this was my workaround ito make it working in wayland session:

**Comment by thknx** [comment] 2019-11-03 18:56
> I had the same problem on Xorg. I think it works with FF because it is using X too instead of wayland. BTW this was my workaround to make it working in wayland session:
> change the `Exec=crow` in **/usr/share/applications/crow-translate.desktop** to `Exec=env QT_QPA_PLATFORM=xcb /usr/bin/crow`

Thank you for your politeness, but likely did't work.
Screen: https://i.ibb.co/qg5PzM6/Screenshot-from-2019-11-03-21-49-30.png

**Comment by Shatur95** [comment] 2019-11-03 18:59
Did you restart the application after the changes?

**Comment by thknx** [comment] 2019-11-03 18:59
Yes, I also rebooted the system.
But result is the same.

**Comment by Shatur95** [comment] 2019-11-03 19:01
The problem seems to be that getting selection only works in Xorg applications. This is a known issue because Wayland doesn't have an API for this yet :(

**Comment by thknx** [comment] 2019-11-03 19:16
I changed system to Xorg now it's working (did't know Crow does not support wayland.
We looking forward for supporting wayland :)

**Comment by Shatur95** [comment] 2019-11-03 21:52
Yes, looking for a solution :)

**Comment by hexauniverse** [comment] 2019-11-04 05:06
> The problem seems to be that getting selection only works in Xorg applications

No, only keyboard shortcuts dont't work. If you select some text on wayland window, you can switch to xorg window and press shortcut, this will work

**Comment by Shatur95** [comment] 2019-11-04 08:13
The selection is works?
Weird, the Qt documentation says that selection is supported [only for X11](https://doc.qt.io/qt-5/qclipboard.html#Mode-enum). Maybe it works because of XWayland.

Yes, global shotcuts needs to be fixed too (just add CLI commands to control GUI).

**Comment by Shatur95** [comment] 2019-11-04 08:18
Duplicate of #73

**Closed** 2019-11-04 08:18 UTC
