### ISSUE TITLE
Unable to install Crow Translate on Debian 12

### ISSUE THREAD

**Issue by peter099** [crow-translate/crow-translate#602] opened 2023-08-10 06:50 UTC
The .deb file of Crow Translate cannot be installed on Debian 12 because of missing dependencies - libtesseract4.

**Comment by Shatur** [comment] 2023-08-10 07:07
Duplicate of #577.

**Closed by Shatur** 2023-08-10 07:07 UTC

**Comment by Shatur** [comment] 2023-08-11 07:11
You missing extra cmake modules, see https://github.com/crow-translate/crow-translate#required

**Comment by peter099** [comment] 2023-08-11 10:09
I installed the package `extra-cmake-modules` which in the debian 12 repository. Now if i try build from source i get this:

`$ cmake ..
CMake Error at CMakeLists.txt:69 (add_subdirectory):
  The source directory

    /home/user/Downloads/crow-translate-2.10.10/src/third-party/singleapplication

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:70 (add_subdirectory):
  The source directory

    /home/user/Downloads/crow-translate-2.10.10/src/third-party/qhotkey

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:71 (add_subdirectory):
  The source directory

    /home/user/Downloads/crow-translate-2.10.10/src/third-party/qtaskbarcontrol

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:72 (add_subdirectory):
  The source directory

    /home/user/Downloads/crow-translate-2.10.10/src/qonlinetranslator

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:77 (find_package):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
`

**Comment by RENANZG** [comment] 2023-11-12 22:40
Yes, libtesseract4 is missing.

<pre>
The following packages have unmet dependencies:
 crow-translate : Depends: libtesseract4 but it is not installable
E: Unable to correct problems, you have held broken packages.
</pre>

Debian 12 uses <code>libtesseract5</code>
```sh
user@host:~$ sudo apt list libtesseract5
Listing... Done
libtesseract5/stable,now 5.3.0-2 amd64 [installed] 
```
You could install with this script, but google tts doesnt work:

[crow-translate.txt](https://github.com/crow-translate/crow-translate/files/13329357/crow-translate.txt)
