### ISSUE TITLE
Ubuntu 20.10 could not start version 2.6.1

### ISSUE THREAD

**Issue by linhnd1303** [crow-translate/crow-translate#214] opened 2020-12-12 09:44 UTC
**Bug description**
Ubuntu 20.10 could not start version 2.6.1. Even I tried to install in many way 

**Environment**

-   OS: Ubuntu
-   Desktop environment: KDE
-   Crow Translate version: 2.6.1

**Comment by Shatur95** [comment] 2020-12-12 10:51
I think it's duplicate of #196. The issue related to the system configuration.

**Closed by Shatur95** 2020-12-12 10:51 UTC
Labels: bug
