### ISSUE TITLE
Non-local interface language(s) is(are) applied

### ISSUE THREAD

**Issue by WhiredPlanck** [crow-translate/crow-translate#391] opened 2022-01-09 00:35 UTC
**Bug description**
Non-local interface language(s) is(are) applied.

For example, if I select Chinese Simplified as my interface language,  *Settings* item in system tray menu will show in other language (Italian I think).

This issue has only been found when the interface language is specified as Simplified Chinese so far.

**Steps to reproduce**

1. Start the application
2. Specify the interface language 
3. Right click on the tray icon to show menu
---
1. Go to 'Settings' page
2. Go to 'General' tab
3. See error in the drop-down menu of 'Main window orientation'.

**Expected behavior**
These items should be shown in the specified language.

**Screenshots**
![图片](https://user-images.githubusercontent.com/47623588/148664348-a2fa9209-0d47-4c50-a340-6ee936aa04c3.png)

![图片](https://user-images.githubusercontent.com/47623588/148664606-f61d10c8-e753-4611-bd88-87935bbc76a4.png)

**Environment**

- OS: Arch Linux / AOSC OS
- Desktop environment: KDE
- Crow Translate version: 2.9.1

**Additional context**

**Comment by Shatur** [comment] 2022-01-09 08:01
Thanks for the info! But the issue is already fixed in the latest master. You will see the correct string in the next release.

**Closed by Shatur** 2022-01-09 08:01 UTC
Labels: bug

**Comment by WhiredPlanck** [comment] 2022-01-23 12:12
> Thanks for the info! But the issue is already fixed in the latest master. You will see the correct string in the next release.

Thank you! (Sorry for late replying)
