### ISSUE TITLE
Ability to set a shortcut for clearing the source

### ISSUE THREAD

**Issue by HubKing** [crow-translate/crow-translate#683] opened 2024-05-19 16:00 UTC
**Describe the problem or limitation you are having**

When keep translating things, I have clear the existing source text. I can do that by clicking the (X) button or by pressing ctrl+a -> del. But one shortcut would be more convenient.

**Describe the solution you'd like**

In settings -> Shortcuts, add "Clear text".

**Describe alternatives you've considered**

**Additional context**

**Comment by Shatur** [comment] 2024-05-20 08:04
Duplicate of #397.

**Closed by Shatur** 2024-05-20 08:04 UTC
Labels: enhancement
