### ISSUE TITLE
Error in translation with google engine

### ISSUE THREAD

**Issue by Joselpdj** [crow-translate/crow-translate#242] opened 2021-02-08 11:23 UTC
**Bug description**
Often when I try to translate texts with google engine I get a translation error: Error transferring https://translate.googleapis.com/translate_a/single?client=gtx&ie=UTF-8&oe=UTF-8&dt=bd&dt=ex&dt=ld&dt=md&dt=rw&dt=rm&dt=ss&dt=t&dt=at&dt=qc&sl=es&tl=en&hl=es&q=A menudo%2C cuando intento traducir textos con el motor de google%2C me aparece un error de traducción%3A - server replied: Too Many Requests

**Steps to reproduce**

1.  Go to crow translate
2.  Click on first window for translate text
3.  Click in translation button or wait to the automatic translation.
4.  See error with a google engine.

**Expected behavior**
The text should be translated it as with the others translation engines.

**Screenshots**
![Crow-translate-bug](https://user-images.githubusercontent.com/65603208/107213075-2e0fc480-6a08-11eb-894f-dfddc406280c.png)

**Environment**

-   OS: Mageia Plasma 8 RC.
-   Desktop environment: Plasma Kde 5.20.4
-   Crow Translate version: 2.7

**Additional context**
I see this error from previous versions.

**Comment by Shatur95** [comment] 2021-02-08 11:25
Duplicate of #105.

**Closed by Shatur95** 2021-02-08 11:25 UTC
Labels: bug
