### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by walnous** [crow-translate/crow-translate#122] opened 2020-05-15 01:24 UTC
Error transferring https://translate.googleapis.com/translate_a/single?client=gtx&ie=UTF-8&oe=UTF-8&dt=bd&dt=ex&dt=ld&dt=md&dt=rw&dt=rm&dt=ss&dt=t&dt=at&dt=qc&sl=auto&tl=pt&hl=pt&q=bid - server replied: Too Many Requests

**Comment by Shatur95** [comment] 2020-05-15 07:16
Duplicate of #105

**Closed by Shatur95** 2020-05-15 07:16 UTC
