### ISSUE TITLE
Save last words

### ISSUE THREAD

**Issue by Jairjua** [crow-translate/crow-translate#82] opened 2019-11-04 11:45 UTC
Suggestion: save the last 100 most researched words. It's useful for who is learning a new language. 
The option for delete and export this words is useful too.

**Comment by Shatur95** [comment] 2019-11-04 11:49
I already have a suggestion for it. Will implement cache and lookup for it.
Duplicate of #25

**Closed by Shatur95** 2019-11-04 11:49 UTC
