### ISSUE TITLE
add shortcut for button "Clear"

### ISSUE THREAD

**Issue by paolomi** [crow-translate/crow-translate#472] opened 2022-08-31 09:21 UTC
Please, add a shortcut for the button "Clear".

Why?
On some occasions, it is faster to delete text with a shortcut than to move your hand over the mouse.

Thanks a lot!

**Comment by Shatur** [comment] 2022-08-31 09:41
Duplicate of #397.

**Closed by Shatur** 2022-08-31 09:41 UTC
Labels: enhancement
