### ISSUE TITLE
Add a shortcut to translate selected text, copy it to clipboard *and* paste it back

### ISSUE THREAD

**Issue by ilyagoz** [crow-translate/crow-translate#546] opened 2023-05-21 18:45 UTC
Add a shortcut to translate selected text, copy it to clipboard **and** immediately paste it back, thus replacing selected text with a translation.

That would help immensely with translation workflow.

Sure, I can paste manually, but translation isn't instant, so I can't press Ctrl-V too quickly, and timing the delay is not convenient.

**Comment by Shatur** [comment] 2023-05-21 20:38
Duplicate of #68.

**Closed by Shatur** 2023-05-21 20:38 UTC
Labels: enhancement
