### ISSUE TITLE
Shortcut to directly replace selected text by the translation (in any application) without calling the main window

### ISSUE THREAD

**Issue by kamaqnkatyqn** [crow-translate/crow-translate#580] opened 2023-07-05 21:37 UTC
When I want to directly replace highlighted text by its translation, I have to use the function "Translate selected text and copy it to the clipboard" (or press the shortcut I select for this) and then press Ctrl + V.

Why not introduce a function where I just have to press one shortcut?

**Comment by Shatur** [comment] 2023-07-05 22:13
Duplicate of #68.

**Closed by Shatur** 2023-07-05 22:13 UTC
Labels: enhancement
