### ISSUE TITLE
wrong keyboard shortcut

### ISSUE THREAD

**Issue by homus32** [crow-translate/crow-translate#212] opened 2020-12-08 10:52 UTC
**Bug description**
The wrong keyboard shortcut is being set. 

**Steps to reproduce**

1.  Go to 'Application Settings'
2.  Click on 'Shortcuts'
3.  Select any shortcut 
4.  Try set "Meta + Alt + C"
5. See error

**Expected behavior**
instead of the normal keyboard shortcut some incomprehensible characters are obtained

**Screenshots**
[My system info](https://i.imgur.com/wjUoAKa.png)
[What the bug looks like](https://i.imgur.com/8tbMhJ9.png)

**Environment**

-   OS: Ubuntu 20.04
-   Desktop environment: KDE 5.20 (kde neon)
-   Crow Translate version: 2.6.1

**Comment by Shatur95** [comment] 2020-12-08 10:55
Hi! Thanks for the report, but it's known Qt issue :(
See [my comment](https://github.com/crow-translate/crow-translate/issues/103#issuecomment-583830442) for a workaround.
Duplicate of #103.

**Closed by Shatur95** 2020-12-08 10:55 UTC
Labels: bug
