### ISSUE TITLE
Settings.ini file no longer working in portable mode

### ISSUE THREAD

**Issue by crazyrabbit0** [crow-translate/crow-translate#583] opened 2023-07-11 12:51 UTC
**Bug description**
Settings.ini file no longer created/used in portable mode since version 2.10.6

**Steps to reproduce**
1. Go to 'Settings'
2. Click on 'Portable mode'
3. Change any other setting
3. Click on 'Ok'
4. settings.ini file is not created

**Expected behavior**
settings.ini file created.

**Environment**
- OS: Windows 10 Pro 22H2  (Build 19045.3086)
- Crow Translate version: 2.10.6

**Additional context**
I tried using putting my old settings.ini file in Crow Translate's folder but this isn't working either

**Comment by Shatur** [comment] 2023-07-11 12:52
Duplicate of #556.

**Closed by Shatur** 2023-07-11 12:52 UTC
Labels: bug

**Comment by crazyrabbit0** [comment] 2023-07-11 12:59
How is this a duplicate of 556;
I was using the previous version of Crow Translate in "Portable mode" with no problem.
The settings.ini file was created in the same folder as the executable.
Now in the latest version, it no longer works, it doesn't create a settings.ini file at all.

**Comment by Shatur** [comment] 2023-07-11 13:01
> How is this a duplicate of 556;

This is exactly what 556 is about. Download the build artifact from https://github.com/crow-translate/crow-translate/actions/runs/5458406815, the issue should be gone. I will draft a new release soon.

**Comment by crazyrabbit0** [comment] 2023-07-11 13:07
My bad, you are actually right.
The #1055 build works as intended 👌
