### ISSUE TITLE
The app's text-to-speech feature is not working properly.

### ISSUE THREAD

**Issue by HM-Huong** [crow-translate/crow-translate#507] opened 2023-01-17 13:25 UTC
**Bug description**
When I try using the app's text-to-speech feature in speech test in settings it says "This percent, 20 is percent, 20 in percent, 20 example percent, 20 of percent, 20 speech percent, 20 synthesis" while the textbox content is "This is an example of speech synthesis.". The same thing happens when I highlight a long phrase and press ctr+alt+s (speak selected text).

**Environment**
- OS: Windows
- Crow Translate version: 2.10.1

**Comment by Shatur** [comment] 2023-01-17 13:59
Duplicate of #410. Currently not sure how to fix.

**Closed by Shatur** 2023-01-17 13:59 UTC
Labels: bug
