### ISSUE TITLE
backward translation

### ISSUE THREAD

**Issue by yrg23** [crow-translate/crow-translate#573] opened 2023-06-30 21:27 UTC
Would you add backward translation to program. I have seen this feature in qtranslate software before. But qtranslate is not getting updates right now. in this feature, after you translated such sentences, in another panel translation is translated to original language again. we are able to change suggested translations also. by this way, we can manipulate translation and see corrections made is semantic or not.

![image](https://github.com/crow-translate/crow-translate/assets/19708317/b0f51389-7e38-4dad-bab5-deb64b076466)

**Comment by Shatur** [comment] 2023-06-30 21:29
Duplicate of #526.
Definitely a good feature, but I currently busy with a different project.
But I would review a PR ASAP.

**Closed by Shatur** 2023-06-30 21:29 UTC
Labels: enhancement
