### ISSUE TITLE
Ctrl+Alt+E problem with flatpak version

### ISSUE THREAD

**Issue by hoshython** [crow-translate/crow-translate#586] opened 2023-07-14 17:57 UTC
version 2.10.3 flatpak installed on fedora 38 kde. Alt+Ctrl+E opens translate window but for whatever reason cannot get highlighted text to translate. Possibly permission problems. Please check that.

**Comment by Shatur** [comment] 2023-07-14 18:02
@gasinvein maybe flatpak requires more permissions to get selection?

**Comment by hoshython** [comment] 2023-07-14 18:03
but which permission?

**Comment by Shatur** [comment] 2023-07-14 18:04
I asked @gasinvein who submitted the application to flatpak.

**Comment by gasinvein** [comment] 2023-07-14 19:24
@Shatur Not really, Flatpak doesn't affect how the app interacts with the display server, it either gives the app access to it or not.
@hoshython What's your DE? Are you running a Wayland or X11 session?

**Comment by hoshython** [comment] 2023-07-14 19:29
@gasinvein KDE on Wayland

**Comment by gasinvein** [comment] 2023-07-14 19:38
Ugh, I've just realized Crow Translate on Flathub is outdated (still at 2.10.3). Let's get it updated first, and then check if this issue persists.

**Comment by Shatur** [comment] 2023-07-14 19:46
Oh, it's duplicate of #324.
Help is appreciated.

**Closed by Shatur** 2023-07-14 19:46 UTC
Labels: bug

**Comment by gasinvein** [comment] 2023-07-14 20:18
Flatpak build fixed in https://github.com/flathub/io.crow_translate.CrowTranslate/pull/21 (there was a problem with tesseract on aarch64), please wait for the update to to land in the repo (usually up to 4 hours) and re-check this issue.
