### ISSUE TITLE
Add Flatpak and flathub support

### ISSUE THREAD

**Issue by trprado** [crow-translate/crow-translate#79] opened 2019-10-29 16:11 UTC
Please add the flatpak application, so it's easy to keep the version updated by flathub.

**Comment by Shatur95** [comment] 2019-10-29 16:37
I do not use Flatpack, so I can not maintain it. Could you help me with it?

**Comment by IROdEvO** [comment] 2020-06-09 19:54
This is a great application but it's unfortunate that the latest version does not support Fedora. A flatpak would be the ideal solution because it can be used by all the Linux distributions and the developers have to maintain only one package. 

I should look into flatpak development. I just don't have the knowledge atm to help.

**Comment by Shatur95** [comment] 2020-06-09 19:56
Btw, Next version will have RPM provided by me. I recently switched ti CMake and now can easy generate packages for most distributions.

**Comment by CohenAriel** [comment] 2022-03-01 16:03
Hello, I was creating the manifest for this but flatpak doesn't allow internet access while building, so fetchcontent can't be used. I'm not experienced with cmake, can you create a flatpak version where the packages install with fetchcontent are added as submodules instead?

**Comment by Shatur** [comment] 2022-03-01 16:27
Hm... I've used submodules before, but this approach also have number of disadvantages, here is the issue #116.
It's a big disadvantage for Flatpack. How Rust packages are built, for example?

**Comment by CohenAriel** [comment] 2022-03-02 12:16
I don't know. Is there any good way to use those packages without downloading them during the build process? The current approach is good but for some reason flathub doesn't allow network access while building https://github.com/flathub/flathub/issues/236

**Comment by Shatur** [comment] 2022-03-02 12:18
Maybe you could somehow run configure step before flatpack?

**Comment by CohenAriel** [comment] 2022-03-02 12:57
I can't. Flathub builds everything, and it only allows internet access to download dependencies before the build starts. Maybe I can build the packages as normal dependencies? I didn't see any build instructions in https://github.com/crow-translate/QOnlineTranslator, https://github.com/Skycoder42/QTaskbarControl, https://github.com/crow-translate/QGitTag and https://github.com/itay-grudev/SingleApplication

**Comment by Shatur** [comment] 2022-03-02 13:00
You can try to download it manually before and put it into `build/_deps` folder as CMake do.

**Comment by CohenAriel** [comment] 2022-03-02 13:25
CMake still tried to download the packages, how do I disable that?

**Comment by Shatur** [comment] 2022-03-02 17:12
Honestly, I don't know :(
Are you sure that you using the same folder structure for dependencies as CMake do? We use `FetchContent` CMake module.
Also maybe it possible to do configuration step before flatpack creation?

**Comment by CohenAriel** [comment] 2022-03-02 20:18
I might've found a way

**Comment by gasinvein** [comment] 2022-05-10 11:01
Network access at build time is an issue not only for Flathub but also for most distro package build systems. E.g. it's a big no-no for Fedora official repos. Maybe you could reconsider using git modules? #116 proposed to release a full source source tarball (with git modules prefetched), and I believe it would've been a better solution than using `FetchContent`.

**Comment by Shatur** [comment] 2022-05-10 11:04
But how do you package python, js or rust programs that download dependencies too?

**Comment by gasinvein** [comment] 2022-05-10 11:09
Distros package each pip/cargo/npm dependency individually (I guess that's why there are little to none Node apps in most official distro repos). For Flathub, pip/cargo/npm dependencies are converted to flatpak-builder manifests (there are tools to automate this), so that dependencies are fetched by flatpak-builder before the build process starts.

**Comment by Shatur** [comment] 2022-05-10 11:12
Hm... But in Rust you can't package cargo dependencies individually, they linked statically. How, for example, `rg` is packaged?

**Comment by Shatur** [comment] 2022-05-10 11:15
In Archlinux [ripgrep](https://archlinux.org/packages/community/x86_64/ripgrep/) depends only on system libraries, all Rust dependencies are loaded and compiled when the package is created.

**Comment by gasinvein** [comment] 2022-05-10 11:17
>But in Rust you can't package cargo dependencies individually, they linked statically

Not sure what others do, but Fedora packages rust crates _sources_ - into a system-wide location where cargo can then find them at build time.

>In Archlinux [ripgrep](https://archlinux.org/packages/community/x86_64/ripgrep/) depends only on system libraries, all Rust dependencies are downloaded and compiled when the package is created

Archlinux is, I believe, the only distro that allows network access at build time, so building with cargo "as usual" is not a problem for them.

**Comment by Shatur** [comment] 2022-05-10 11:23
> Not sure what others do, but Fedora packages rust crates sources

Rust programs have thousand of dependencies. And each program could use a different version. [Here](https://github.com/carlwgeorge/ripgrep-rpm/blob/master/ripgrep.spec) is how spec file looks in Fedora Copr, for example.

**Comment by gasinvein** [comment] 2022-05-10 11:26
> > Not sure what others do, but Fedora packages rust crates sources
> 
> Rust programs have thousand of dependencies. And each program could use a different version. [Here](https://github.com/carlwgeorge/ripgrep-rpm/blob/master/ripgrep.spec) is how spec file looks in Fedora Copr, for example.

Yes, thus its largely automated in Fedora. The magic happens in the `%cargo_generate_buildrequires` macro.

**Comment by gasinvein** [comment] 2022-05-10 11:45
> Maybe you can run configure CMake step (which downloads dependencies) before the build step?

It still won't have network access, since it's a part of the project build process. Running it in a different (network-enabled) environment would eliminate the whole point of running builds offline (that is ensuring reproducibility).

>Because using submodules becomes a pain for ArchLinuix and Solus...

Right, thus #116 proposed to provide a full source tarball with each tagged release.

**Comment by Shatur** [comment] 2022-05-10 11:54
> Running it in a different (network-enabled) environment would eliminate the whole point of running builds offline (that is ensuring reproducibility).

But dependencies are fixed by checksums, they will always be reproducible even when downloading? You you afraid that the download source could be down?

> Right, thus https://github.com/crow-translate/crow-translate/issues/116 proposed to provide a full source tarball with each tagged release.

Oh, I see. Yes, this should work. But it's pitty that can't use built-in CMake solution for it... But packaging is important. I currently busy at the moment, but maybe anyone could help me automate the process?

**Comment by gasinvein** [comment] 2022-05-10 12:00
> > Running it in a different (network-enabled) environment would eliminate the whole point of running builds offline (that is ensuring reproducibility).
> 
> But dependencies are fixed by checksums, they will always be reproducible even when downloading?

With Cargo, mostly yes. Not really the case with PIP or NPM - they can run arbitrary code at dependency install time and download arbitrary things outside the NPM registry, and it's quite common practice for Node packages.

**Comment by gasinvein** [comment] 2022-05-10 12:01
> Or maybe you can somehow package the dependencies and share if with `FetchContent` as you do for programs in other languages? There a few, shouldn't be hard do do it manually.

You mean look for system-installed dependencies and fall back to `FetchContent` only if they're not found? This is probably the most packaging-friendly approach, yes, but it'll require the most effort, I guess.

**Comment by Shatur** [comment] 2022-05-10 12:23
> You mean look for system-installed dependencies and fall back to FetchContent only if they're not found?

Yep. Package sources as you do for Cargo, but somehow ask `FetchContent` to look system wide. If there is no such built-in feature in `FetchContent`, I could introduce CMake variables for each dep which you can fill at build time with path to system packages. What do you think?

**Comment by gasinvein** [comment] 2022-05-10 12:27
> somehow ask `FetchContent` to look system wide.

I guess `FetchContent` has no builtin fallback mechanism.

> I could introduce CMake variables for each dep which you can fill at build time with path to system packages. What do you think?

Are all the deps installable as libraries? Packaging source for C/C++ projects is not common (and probably not acceptable) for distros. The usual way to go is to builds the dependency as a library, then, in the dependent project, look for the library via CMake's `FindPackage` or pkg-config.

**Comment by Shatur** [comment] 2022-05-10 12:36
> Are all the deps installable as libraries?

No, as sources.

> The usual way to go is to builds the dependency as a library, then, in the dependent project, look for the library via CMake's find_package or pkg-config.

You are right, this is how it usually done for **shared libraries**. Such libraries honor ABI and you can link multiply programs or other libs to them for reuse. And I link this way to Qt and Tesseract. But this is not the case with a [this](https://github.com/crow-translate/crow-translate/blob/master/cmake/ExternalLibraries.cmake) dependencies. They indented to linked statically (some of them could be even header-only). In most old projects such libraries / headers just copy-pasted to the project repo. But with modern CMake we can download it at configuration time as usually Cargo do.

**Comment by gasinvein** [comment] 2022-05-10 12:43
> > Are all the deps installable as libraries?
> 
> No, as sources.

Then I guess git submodules fit better for this case.

> > The usual way to go is to builds the dependency as a library, then, in the dependent project, look for the library via CMake's find_package or pkg-config.
> 
> You are right, this is how it usually done for **shared libraries**. Such libraries honor ABI and you can link multiply programs or other libs to them for reuse. And I link this way to Qt and Tesseract. But this is not the case with a [this](https://github.com/crow-translate/crow-translate/blob/master/cmake/ExternalLibraries.cmake) dependencies. They indented to be linked statically because they don't honor ABI (and some of them could be even header-only!). In most old C / C++ projects such libraries / headers just copy-pasted to the project repo. But with modern CMake we can download it at configuration time as usually Cargo do.

Well, QtSingleApplication is a common example of a static-only library. Other Qt apps (see e.g. qBittorrent) usually add it as a git submodule.

**Comment by Shatur** [comment] 2022-05-10 12:47
Okay, let's migrate back to submodules then. But I currently busy with another project, so help in automation is very welcome (need to upload source release with all submodules on release using GitHub Actions)!

**Comment by Shatur** [comment] 2022-05-10 21:44
Drafted a new release. Feel free to update installation if you packaging for your distro to let users know about it :)

**Comment by gasinvein** [comment] 2022-05-10 21:58
Flathub requires apps to provide [metainfo](https://freedesktop.org/software/appstream/docs/chap-Metadata.html). It can be added downstream (in external repo, for flatpak only), but since it's also beneficial for deb and rpm repos, consider adding one to the app repo and installing it for all Linux builds.

**Comment by Shatur** [comment] 2022-05-10 22:08
Didn't know about it! I would like to have something like this. But currently busy. Maybe someone interested in Flatpack could contribute it?

**Comment by gasinvein** [comment] 2022-05-10 22:18
Sure, you go: #420. Please try to keep it up to date, since it contains metadata that users will see in their stores frontends (like Gnome Software and KDE Discover).

**Comment by Shatur** [comment] 2022-05-10 22:38
Bumped a new release.

**Comment by Shatur** [comment] 2022-05-11 15:12
The more I think about it, the less I like the idea of ​​using submodules. You can forgot to clone them, it's inconvenient to work with it, it downloads all deps while you may need only specific depending on specific defines and big submodules slowdows my machine. If mature C++ projects use submodules it doesn't mean that all other new should use it too. Modern CMake encourages using `FetchContent` like all modern languages do. I think package systems which doesn't support internet connection during build could use `FETCHCONTENT_UPDATES_DISCONNECTED` and put all submodules manually before the build.

**Comment by gasinvein** [comment] 2022-05-11 18:09
Meson has wrap-files to define build-time-downloaded external subprojects, and has builtin `meson dist` command to pack complete source release tarball with subprojects included. Maybe CMake has something analogous, but I didn't hear anything about the like.

> I think package systems which doesn't support internet connection during build could use `FETCHCONTENT_UPDATES_DISCONNECTED` and put all submodules manually before the build.

It will drastically increase the required amount of work for the package maintainer on every release of your app. When there is a complete source available (i.e. a release tarball), updating the app package is usually as easy as bumping the version number. But going through all the dependencies in CMake manually and bumping their versions would be different story.

**Comment by Shatur** [comment] 2022-05-11 18:42
> Meson has wrap-files to define build-time-downloaded external subprojects, and has builtin meson dist command to pack complete source release tarball with subprojects included.

That's a cool feature. Sadly CMake doesn't have such thing :(

> It will drastically increase the required amount of work for the package maintainer on every release of your app. When there is a complete source available (i.e. a release tarball), updating the app package is usually as easy as bumping the version number. But going through all the dependencies in CMake manually and bumping their versions would be different story.

Hmm... I agree, better to stick with submodules, it's the lesser evil.

**Comment by gasinvein** [comment] 2022-05-11 19:22
Now that everything seems in place, I believe the app can be published to Flathub. If you don't want to maintain it yourself, I can submit it if you don't mind (although note that Flathub strongly prefers apps to be maintained by first parties).

FWIW I didn't hear about Crow Translate before yesterday and wandered into this thread mostly by accident, investigating on the other guy's behalf why the app isn't available from official Fedora repos. But the app appeared pretty cool and I think I'm going to use it, so now I'd like to have it available on Flathub, too.

**Comment by Shatur** [comment] 2022-05-11 19:31
> Now that everything seems in place, I believe the app can be published to Flathub. If you don't want to maintain it yourself, I can submit it if you don't mind (although note that Flathub strongly prefers apps to be maintained by first parties).

Feel free to submit it! I don't use Flatpak myself, so I can't properly maintain it.
Is there anything needed from me to get the app submitted? If no, I going to draft a new minor release with the app running dialog removal.

> But the app appeared pretty cool and I think I'm going to use it

Nice to hear!

**Comment by gasinvein** [comment] 2022-05-11 19:36
> Is there anything needed from me to get the app submitted?

Basically just your consent. When it's accepted, Flathub admins may send you invitation to collaborate on the git repo created under the flathub org - make sure to accept, just in case, even if you're not going to maintain it.

**Comment by Shatur** [comment] 2022-05-11 20:30
Merged some fixes in the release preparation. Publishing?

**Comment by gasinvein** [comment] 2022-05-11 20:34
Yeah, I think we should be good to go.

**Comment by Shatur** [comment] 2022-05-11 20:35
Okay, done!

**Comment by gasinvein** [comment] 2022-05-11 20:43
Submitted to Flathub for review, see the link above.

**Comment by Shatur** [comment] 2022-05-13 11:35
Great! Any change you could submit instruction to [installation.md](https://github.com/crow-translate/crow-translate.github.io/blob/master/content/en/home/installation.md)?

**Closed by Shatur** 2022-05-13 11:35 UTC
Labels: help wanted

**Comment by CohenAriel** [comment] 2022-05-13 11:47
https://github.com/crow-translate/crow-translate.github.io/pull/2
@Shatur
