### ISSUE TITLE
Recommend feature

### ISSUE THREAD

**Issue by VDuck02** [crow-translate/crow-translate#585] opened 2023-07-12 14:00 UTC
Hello, can you add a "change selected text" feature, for example I write text and characters in notpad, I highlight them and use a certain keyboard shortcut, the characters I highlight will automatically is it possible to switch to secondary language!!?

Thanks for reading!

**Comment by Shatur** [comment] 2023-07-12 14:01
Duplicate of #68.

**Closed as completed by Shatur** 2023-07-12 14:01 UTC
Labels: enhancement
