### ISSUE TITLE
Text capture does not occur when text is selected in version 2.10.9

### ISSUE THREAD

**Issue by pavonz** [crow-translate/crow-translate#598] opened 2023-08-02 07:38 UTC
**Text capture does not occur when text is selected in version 2.10.9**

**Steps to reproduce**

**Expected behavior**

![20230802_09 37 48 061](https://github.com/crow-translate/crow-translate/assets/1979054/02fe13a6-4c5e-4ae2-ac9e-89a04815079b)
**Environment**

- OS: 
- Crow Translate version: 

**Additional context**

**Comment by Shatur** [comment] 2023-08-02 07:39
Duplicate of #597

**Closed by Shatur** 2023-08-02 07:39 UTC
Labels: bug
