### ISSUE TITLE
Please make a "dark mode" option

### ISSUE THREAD

**Issue by DarkameMaster** [crow-translate/crow-translate#669] opened 2024-03-26 09:08 UTC
I have dark mode enabled on Windows but the app doesn't change the mode, if there was an option available in settings that would be awesome

An alternative that I found is enabling high contrast mode but it makes Windows look uglier :( 

This is not related but I would also suggest to make an option that can instantly translate from the clipboard! That would help a lot

**Comment by b-risk** [comment] 2024-05-06 23:54
I would like this as well, (I'm on Linux Mint).

**Comment by Shatur** [comment] 2024-05-07 00:07
Duplicate of #487.

**Closed by Shatur** 2024-05-07 00:07 UTC
Labels: enhancement
