### ISSUE TITLE
Replace

### ISSUE THREAD

**Issue by boromyr** [crow-translate/crow-translate#118] opened 2020-05-09 18:05 UTC
Can I propose to add the replacement functionality of the translated text directly from the popup? I think it could be a useful feature for everyone, with which you could quickly translate documents without altering the formatting too much.
I hope it's not a difficult proposal, I was thinking of recording a macro to do this, but I think the end result would be disappointing.

Thank you for this software.

**Comment by Shatur95** [comment] 2020-05-09 18:30
Duplicate of #68

**Closed by Shatur95** 2020-05-09 18:30 UTC
Labels: enhancement
