### ISSUE TITLE
replace selected text with translation

### ISSUE THREAD

**Issue by azjio** [crow-translate/crow-translate#224] opened 2021-01-03 11:39 UTC
How about inserting a translation using xdotool?
It is necessary to translate many lines with comments in the source.
If I translate text to the clipboard to insert instead of the existing text, then why not exclude an unnecessary hotkey call.

**Comment by Shatur95** [comment] 2021-01-03 12:21
Duplicate of #68.

> How about inserting a translation using xdotool?

I am against such methods in native programs. It can be done using system calls.

**Closed by Shatur95** 2021-01-03 12:21 UTC
Labels: enhancement

**Comment by azjio** [comment] 2021-01-03 17:52
The QTranslate app has this feature
http://forum.ru-board.com/topic.cgi?forum=5&topic=35038
https://quest-app.appspot.com/download

**Comment by Shatur95** [comment] 2021-01-03 17:55
> The QTranslate app has this feature

I know. I meant that it should be done via native calls.

**Comment by azjio** [comment] 2021-01-03 18:09
I was looking for a software way to insert the text and didn't find it.
I found a comment in the Parcellite program that if you want to automatically insert text, then install xdotool.
You can check the existence of xdotool at the start of your program and determine whether to use an insert.
